<?php

function site_lang_normalize($value): string {
    $value = strtolower(trim((string)$value));
    return $value === 'en' ? 'en' : 'ru';
}

function site_lang_set(string $lang): void {
    $lang = site_lang_normalize($lang);
    $_SESSION['ui_lang'] = $lang;
    $GLOBALS['__site_lang_cache'] = $lang;
    $secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');
    setcookie('ui_lang', $lang, [
        'expires' => time() + 60 * 60 * 24 * 365,
        'path' => '/',
        'secure' => $secure,
        'httponly' => false,
        'samesite' => 'Lax',
    ]);
}

function site_lang_default(): string {
    global $db;
    if (isset($GLOBALS['__site_lang_default']) && $GLOBALS['__site_lang_default'] !== null && $GLOBALS['__site_lang_default'] !== '') {
        return site_lang_normalize((string)$GLOBALS['__site_lang_default']);
    }
    $fallback = 'en';
    if (isset($db) && $db instanceof PDO) {
        try {
            $st = $db->prepare('SELECT value FROM meta WHERE key = ? LIMIT 1');
            $st->execute(['ui_lang_default']);
            $v = $st->fetchColumn();
            if ($v !== false && $v !== null && $v !== '') {
                $fallback = site_lang_normalize((string)$v);
            }
        } catch (Exception $e) {
        }
    }
    $GLOBALS['__site_lang_default'] = $fallback;
    return $fallback;
}

function site_lang_default_set(string $lang): void {
    $lang = site_lang_normalize($lang);
    $GLOBALS['__site_lang_default'] = $lang;
}

function site_lang(): string {
    if (!empty($GLOBALS['__site_lang_cache'])) {
        return site_lang_normalize((string)$GLOBALS['__site_lang_cache']);
    }
    if (!empty($_SESSION['ui_lang'])) {
        $cached = site_lang_normalize($_SESSION['ui_lang']);
        $GLOBALS['__site_lang_cache'] = $cached;
        return $cached;
    }
    if (!empty($_COOKIE['ui_lang'])) {
        $cached = site_lang_normalize($_COOKIE['ui_lang']);
        $GLOBALS['__site_lang_cache'] = $cached;
        return $cached;
    }
    $cached = site_lang_default();
    $GLOBALS['__site_lang_cache'] = $cached;
    return $cached;
}

function site_lang_is_en(): bool {
    return site_lang() === 'en';
}

function site_lang_en_map(): array {
    static $map = null;
    if (is_array($map)) {
        return $map;
    }
    $map = [
        'Привет, ' => 'Hello, ',
        'Регистрация' => 'Sign Up',
        'Вход' => 'Log In',
        'Помощь' => 'Help',
        'Выйти' => 'Log Out',
        'Админ-панель' => 'Administration',
        'Главная' => 'Home',
        'Смотреть&nbsp;видео' => 'Watch Videos',
        'Загрузить&nbsp;видео' => 'Upload Videos',
        'Пригласить&nbsp;друзей' => 'Invite Friends',
        'Мои видео' => 'My Videos',
        'Мой канал' => 'My Channel',
        'Избранное' => 'Favorites',
        'Их видео' => 'Their Vids',
        'Их избранное' => 'Their Favs',
        'ToDo...' => 'ToDo List...',
        'Мои друзья' => 'My Friends',
        'Настройки' => 'My Profile',
        'Искать видео' => 'Search Videos',
        'Что нового?' => "What's New?",
        'Что нового' => "What's New",
        'О сайте' => 'About Us',
        'О нас' => 'About Us',
        'Исходный код' => 'Source Code',
        'Последние' => 'Recent',
        'Популярные' => 'Most Viewed',
        'Высоко оцененные' => 'Top Rated',
        'Обсуждаемые' => 'Most Discussed',
        'Избранные' => 'Top Favorites',
        'Случайные' => 'Random',
        'Для вас' => 'For You',
        'Настройки аккаунта' => 'My Account',
        'Перейти к каналу' => 'View My Channel',
        '* Показывает обязательное поле.' => '* Indicates required field.',
        'Удалить мой аккаунт' => 'Delete My Account',
        'Данные успешно сохранены!' => 'Your changes have been saved!',
        'Настройки сайта' => 'Site Settings',
        'Язык:' => 'Language:',
        'закрыть' => 'close',
        'Русский' => 'Russian',
        'English' => 'English',
        'на' => 'on',
        'Спасибо за оценку!' => 'Thanks for rating!',
        'Видео продвинуто в блоке популярных.' => 'Video promoted in the featured block.',
        'Теневой бан для канала включен.' => 'Shadow ban enabled for this channel.',
        'оценок' => 'ratings',
        'Канал не найден' => 'Channel not found',
        'Комментарии о пользователе' => 'Comments about this user',
        'Текст новости (рус.):' => 'News text (RU):',
        'Текст новости (англ.):' => 'News text (EN):',
        'Тип плеера:' => 'Player type:',
        'Автоматический выбор (рекомендуется)' => 'Automatic (recommended)',
        'Всегда Flash плеер' => 'Always Flash player',
        'Всегда HTML5 плеер' => 'Always HTML5 player',
        'Блок на главной:' => 'Homepage module:',
        'Недавно добавленные' => 'Recently Added',
        'Недавно просмотренные' => 'Recently Viewed',
        'Недавно добавленные...' => 'Recently Added...',
        'Недавно просмотренные...' => 'Recently Viewed...',
        'Рекомендации:' => 'Recommendations:',
        'Включить персональные рекомендации' => 'Enable personalized recommendations',
        'Логотип:' => 'Logo:',
        'Смена пароля' => 'Change Password',
        'Старый пароль:' => 'Current Password:',
        'Новый пароль:' => 'New Password:',
        'Повторите новый пароль:' => 'Re-type New Password:',
        'Обновить профиль' => 'Update Profile',
        'Пароль успешно изменён!' => 'Password updated!',
        'Имя:' => 'First Name:',
        'Фамилия:' => 'Last Name:',
        'Дата рождения:' => 'Birthday:',
        'Пол:' => 'Gender:',
        'Не указан' => 'Unspecified',
        'Мужской' => 'Male',
        'Женский' => 'Female',
        'Семейное положение:' => 'Relationship Status:',
        'Не указано' => 'Unspecified',
        'Холост/Не замужем' => 'Single',
        'В отношениях' => 'Taken',
        'Личный сайт:' => 'Personal Website:',
        'Личные данные' => 'Personal Details',
        'О себе:' => 'About Me:',
        '(Расскажите о себе)' => '(Tell us about yourself)',
        'Информация о местоположении' => 'Location Information',
        'Текущая страна:' => 'Country:',
        'Родной город:' => 'Hometown:',
        'Текущий город:' => 'Current City:',
        'Обо мне:' => 'About Me:',
        'Электронная почта:' => 'Email:',
        'Имя пользователя:' => 'User Name:',
        'Пароль:' => 'Password:',
        'Вход в RetroShow' => 'RetroShow Log In',
        'Что такое RetroShow?' => 'What is RetroShow?',
        'Зарегистрируйтесь сейчас' => 'Sign up now',
        'Введите имя пользователя и пароль.' => 'Please enter your username and password.',
        'Неверный логин или пароль.' => 'Invalid username or password.',
        'Канал не найден' => 'Channel not found',
        'Комментарии' => 'Comments',
        'Комментариев пока нет.' => 'No comments yet.',
        'ответить' => 'reply',
        'удалить' => 'delete',
        'Добавить' => 'Comment',
        'Комментарий не может быть пустым!' => 'Comment cannot be empty!',
        'Комментарий слишком длинный (макс. 500 символов)!' => 'Comment is too long (max 500 characters)!',
        'Нельзя прикрепить это видео.' => 'You cannot attach this video.',
        'Только для зарегистрированных пользователей!' => 'Members only!',
        'Не удалось сохранить комментарий. Попробуйте ещё раз.' => 'Could not save the comment. Please try again.',
        'Спасибо. Ваш комментарий успешно опубликован!' => 'Thanks! Your comment was posted.',
        'Ошибка при отправке комментария!' => 'Error posting comment!',
        'Ошибка связи при отправке комментария!' => 'Connection error while posting comment!',
        'Удалить комментарий?' => 'Delete this comment?',
        'Добавить в избранное' => 'Save to Favorites',
        'Убрать из избранного' => 'Remove from Favorites',
        'Войти, чтобы добавить в избранное' => 'Log in to add to Favorites',
        'Добавлено в избранное.' => 'Added to Favorites.',
        'Убрано из избранного.' => 'Removed from Favorites.',
        'Не удалось обновить избранное. Попробуйте ещё раз.' => 'Could not update Favorites. Please try again.',
        'Просмотров:' => 'Views:',
        'Комментариев:' => 'Comments:',
        'Понравилось:' => 'Favorited:',
        'раз' => 'times',
        'Скачать видео в AVI' => 'Download AVI',
        'или' => 'or',
        'Добавлено:' => 'Added:',
        'от' => 'by',
        'пользователем' => 'by',
        'Время:' => 'Time:',
        'Просмотров:' => 'Views:',
        'Видео не найдено.' => 'Video not found.',
        'Видео просмотрено:' => 'Videos Watched:',
        'Видео:' => 'Videos:',
        'Избранных:' => 'Favorites:',
        'Видео' => 'Videos',
        'Друзья' => 'Friends',
        'Загрузка видео' => 'Upload Video',
        'Результаты поиска: ' => 'Search Results: ',
        'Сообщения' => 'Inbox',
        'Сообщение' => 'Message',
        'Друзья' => 'Friends',
        'Пригласить друзей' => 'Invite Friends',
        'Редактирование видео' => 'Edit Video',
        'Удаление видео' => 'Delete Video',
        'Удаление аккаунта' => 'Delete Account',
        'Связаться с нами' => 'Contact Us',
        'Забыли пароль' => 'Forgot Password',
        'Забыли имя пользователя' => 'Forgot Username',
        'Смена пароля' => 'Reset Password',
        'Ежемесячный конкурс' => 'Monthly Contest',
        'Администрирование' => 'Administration',
        'Условия использования' => 'Terms of Use',
        'Политика конфиденциальности' => 'Privacy Policy',
        'Пока нет новостей. Загляните позже!' => 'No news yet. Check back later!',
        'только что' => 'just now',
        'назад' => 'ago',
        'секунду' => 'second',
        'секунды' => 'seconds',
        'секунд' => 'seconds',
        'минуту' => 'minute',
        'минуты' => 'minutes',
        'минут' => 'minutes',
        'час' => 'hour',
        'часа' => 'hours',
        'часов' => 'hours',
        'день' => 'day',
        'дня' => 'days',
        'дней' => 'days',
        'неделю' => 'week',
        'недели' => 'weeks',
        'недель' => 'weeks',
        'месяц' => 'month',
        'месяца' => 'months',
        'месяцев' => 'months',
        'год' => 'year',
        'года' => 'years',
        'лет' => 'years',
        'Оцените видео' => 'Rate this video',
        'Спасибо за оценку!' => 'Thanks for rating!',
        'оценок' => 'ratings',
        'Связанные видео' => 'Related Videos',
        'Комментарии (всего ' => 'Comments (',
        'января' => 'January',
        'февраля' => 'February',
        'марта' => 'March',
        'апреля' => 'April',
        'мая' => 'May',
        'июня' => 'June',
        'июля' => 'July',
        'августа' => 'August',
        'сентября' => 'September',
        'октября' => 'October',
        'ноября' => 'November',
        'декабря' => 'December',
        'Воскресенье' => 'Sunday',
        'Понедельник' => 'Monday',
        'Вторник' => 'Tuesday',
        'Среда' => 'Wednesday',
        'Четверг' => 'Thursday',
        'Пятница' => 'Friday',
        'Суббота' => 'Saturday',
        'Теги //' => 'Tags //',
        'Последние теги //' => 'Latest Tags //',
        'Популярные теги //' => 'Most Popular Tags //',
        'Тегов пока нет!' => 'No tags yet!',
        'Тегов пока нет.' => 'No tags yet.',
        'Недавние теги:' => 'Recent Tags:',
        'Больше тегов' => 'More Tags',
        'Мой аккаунт' => 'My Account Overview',
        'Видео просмотрено:' => 'Videos watched:',
        'Видео:' => 'Videos:',
        'Просмотров:' => 'Views:',
        'Избранных:' => 'Favorites:',
        'Друзей:' => 'Friends:',
        '* Фанатов:' => '* Fans:',
        '* Количество пользователей, добавивших ваши видео в избранное' => '* The number of users that added your videos as a favorite',
        'Количество пользователей, добавивших ваши видео в избранное' => 'The number of users that added your videos as a favorite',
        'У вас' => 'You have',
        'новых сообщений' => 'new messages',
        'Пригласите своих друзей' => 'Invite Your Friends',
        'Кастомизируйте свой профиль' => 'Update Your Profile',
        'Смотрите' => 'Watch',
        'Загружайте' => 'Upload',
        'Делитесь' => 'Share',
        'Загружайте и делитесь видео по всему миру!' => 'Upload, tag and share your videos worldwide!',
        'Загружайте и делитесь видео по всему миру! ' => 'Broadcast Yourself.',
        'закрыть' => 'close',
        'Мгновенно находите и смотрите тысячи видео.' => 'Instantly find and watch 1000\'s of fast streaming videos.',
        'Быстро загружайте видео практически в любом формате.' => 'Quickly upload and tag videos in almost any video format.',
        'Легко делитесь своими видео с семьей, друзьями или коллегами.' => 'Easily share your videos with family, friends, or co-workers.',
        'Рекомендованное для вас' => 'Recommended for You',
        'Больше похожих видео...' => 'See more similar videos...',
        'Популярные видео сегодня' => 'Today\'s Popular Videos',
        'Больше видео' => 'More Videos',
        'Зарегистрируйтесь бесплатно!' => 'Sign up for a free account!',
        'Последние 8 каналов...' => 'Last 8 Users Online...',
        'Последние 4 канала...' => 'Last 4 Users Online...',
        'Иконки означают:' => 'Icon Key:',
        'Добавлено:' => 'Added:',
        'от' => 'by',
        'пользователем' => 'by',
        'Время:' => 'Time:',
        'Комментариев:' => 'Comments:',
        'Оцените видео' => 'Rate this video',
        'Оцените&nbsp;видео' => 'Rate this video',
        'Спасибо за оценку!' => 'Thanks for rating!',
        'Прокомментируйте видео:' => 'Comment on this video:',
        '- Ваши видео -' => '- Your Videos -',
        '- Избранные видео -' => '- Favorite Videos -',
        'О видео' => 'About This Video',
        'Загружено' => 'Added',
        'Настройки видео:' => 'Video settings:',
        'Редактировать' => 'Edit Video',
        'Администрирование:' => 'Administration:',
        'Вставка' => 'Embed',
        'Посмотрите больше видео' => 'Related Videos',
        'Автор:' => 'From:',
        'только что' => 'just now',
        'Видео не найдено.' => 'Video not found.',
        'Ваше видео конвертируется! Скоро он будет доступно к просмотру.' => 'Your video is being converted! It will be available to watch soon.',
        'Автор забанен, канал и все его видео удалены.' => 'The author was banned; the channel and all videos were removed.',
        'Что такое RetroShow?' => 'What is RetroShow?',
        'RetroShow — это способ донести ваши видео до людей, которые важны для вас. С RetroShow вы можете:' => 'RetroShow is a way to get your videos to the people who matter to you. With RetroShow you can:',
        'Показывать любимые видео всему миру' => 'Show off your favorite videos to the world',
        'Делиться видео, снятыми на камеру или телефон' => 'Blog the videos you take with your digital camera or cell phone',
        'Приватно показывать видео друзьям и семье по всему миру' => 'Securely and privately show videos to your friends and family around the world',
        '... и многое другое!' => '... and much, much more!',
        'Чтобы узнать больше о нашем сервисе, посетите раздел' => 'To learn more about our service, please see our',
        'Вход в RetroShow' => 'Log in to RetroShow',
        'Введите имя пользователя и пароль.' => 'Please enter your username and password.',
        'Неверный логин или пароль.' => 'Invalid username or password.',
        'Пожалуйста, введите данные вашего аккаунта ниже. Все поля обязательны.' => 'Please enter your account information below. All fields are required.',
        'Email адрес:' => 'Email Address:',
        'Проверка:' => 'Verification:',
        '(защита от спам-ботов)' => '(spam bot check)',
        '- Я подтверждаю, что мне больше 13 лет.' => '- I certify that I am over 13 years old.',
        '- Я согласен с' => '- I agree to the',
        'условиями использования' => 'Terms of Use',
        'и' => 'and',
        'политикой конфиденциальности' => 'Privacy Policy',
        'Пожалуйста, подождите...' => 'Please wait...',
        'Или' => 'Or',
        'вернуться на главную' => 'return to the home page',
        'Условия использования' => 'Terms of Use',
        'Политика конфиденциальности' => 'Privacy Policy',
        'Про RetroShow' => 'About RetroShow',
        'Пока нет новостей. Загляните позже!' => 'No news yet. Check back later!',
        'Приватные видео' => 'Private Videos',
        'Профиль' => 'Profile',
        'Ссылки' => 'Links',
        'Рекомендуемые' => 'Featured',
        'Рекомендованные' => 'Recommended',
        'видео' => 'Videos',
        'Страница:' => 'Page:',
        'Стр.' => 'Page',
        'Далее' => 'Next',
        'Комм.' => 'Comments',
        'Мои избранные видео' => 'My Favorite Videos',
        'Избранные // ' => 'Favorites // ',
        'Друзья // ' => 'Friends // ',
        'Этот пользователь не добавил ничего в избранное.' => 'This user has not added any favorites.',
        'Войдите или выберите пользователя для просмотра друзей.' => 'Log in or choose a user to view friends.',
        'Этот пользователь не добавил ни одного друга.' => 'This user has not added any friends yet.',
        'Удалить из друзей' => 'Remove from Friends',
        'Удалить видео' => 'Remove Video',
        'Любимые теги:' => 'Favorite Tags:',
        'Мои теги:' => 'My Tags:',
        'Похожие теги:' => 'Related Tags:',
        'Результаты поиска: ' => 'Search Results: ',
        'Не найдено видео по запросу' => 'No videos found for',
        'Лента для тега // ' => 'RSS Feed for Tag // ',
        'Входящие сообщения' => 'Inbox Messages',
        'Сообщения' => 'Messages',
        'Сообщения // Входящие' => 'Messages // Inbox',
        'Сообщение' => 'Message',
        'От' => 'From',
        'Дата' => 'Date',
        'Загрузка видео' => 'Video Upload',
        'Загрузка видео (Шаг 1 из 2)' => 'Video Upload (Step 1 of 2)',
        'Загрузка видео (Шаг 2 из 2)' => 'Video Upload (Step 2 of 2)',
        'Далее ->' => 'Continue ->',
        'Загрузка...' => 'Uploading...',
        'Показ:' => 'Broadcast:',
        'Публично' => 'Public',
        'Приватно' => 'Private',
        'Загрузить видео' => 'Upload Video',
        'Публичное видео' => 'Public Video',
        'Приватное видео' => 'Private Video',
        'Идёт конвертация...' => 'Converting...',
        'Файл:' => 'File:',
        'Статус:' => 'Status:',
        'Канал не найден!' => 'Channel not found!',
        'Это ваш профиль' => 'This is your profile',
        'Вы уже друзья.' => 'You are already friends.',
        'Добавить друга' => 'Add Friend',
        'войдите' => 'log in',
        'чтобы добавить друга' => 'to add a friend',
        'Хотите связаться?' => 'Question? Comment?',
        'Пишите мне!' => 'Contact Me!',
        'Обо мне:' => 'About Me:',
        'Веб-сайт:' => 'Website:',
        'Родной город:' => 'Hometown:',
        'Текущий город:' => 'Current City:',
        'Текущая страна:' => 'Current Country:',
        'Последний вход:' => 'Last Login:',
        'Последнее видео' => 'Latest Video',
        'Нравятся мои видео?' => 'Like my videos?',
        'Подпишитесь на RSS.' => 'Subscribe to my RSS feed.',
        'Оставить комментарий' => 'Add Comment',
        'Оставить новый комментарий' => 'Add a New Comment',
        'Отправить комментарий' => 'Post Comment',
        'Скачать комментарии (.txt)' => 'Download comments (.txt)',
        'Нет комментариев.' => 'No comments.',
        'Зарегистрируйтесь сейчас' => 'Sign up now',
        'и откройте бесплатный аккаунт.' => 'and open a free account.',
        'и создайте бесплатный аккаунт.' => 'and create a free account.',
        'Пригласить друзей' => 'Invite Friends',
        'Приглашения отправлены!' => 'Invites sent!',
        'Приглашения не отправлены! Попробуйте еще раз.' => 'Invites were not sent! Please try again.',
        'Отправить приглашения' => 'Send Invites',
        'Сообщение:' => 'Message:',
        'Оценка' => 'rating',
        'Оценки' => 'ratings',
        'Оценок' => 'ratings',
        'В: Какие видео я могу загружать?' => 'Q: What kind of videos can I upload?',
        'В: Какова продолжительность моего видео?' => 'Q: How long can my video be?',
        'В: Какие форматы видеофайлов я могу загружать?' => 'Q: What video file formats can I upload?',
        'В: Как я могу улучшить свои видео?' => 'Q: How can I improve my videos?',
        'В: Сохраняю ли я авторские права и другие законные права на свои видео?' => 'Q: Do I retain copyrights and other legal rights to my videos?',
        'В: Какова ваша политика в отношении нарушения авторских прав?' => 'Q: What is your policy on copyright infringement?',
        'В: Как сообщить о нарушении авторских прав?' => 'Q: How do I report copyright infringement?',
        'В: Что делать, если меня ложно обвинили в нарушении авторских прав?' => 'Q: What if I am falsely accused of copyright infringement?',
        'В: Что вы делаете, чтобы предотвратить появление на RetroShow контента, нарушающего ваши правила?' => 'Q: What do you do to prevent content that violates your policies from appearing in RetroShow?',
        'Связь с администрацией' => 'Contact Us',
        'Комментарий не может быть пустым!' => 'Comment cannot be empty!',
        'Комментарий слишком длинный (макс. 500 символов)!' => 'Comment is too long (max 500 characters)!',
        'Нельзя прикрепить это видео.' => 'You cannot attach this video.',
        'Не удалось сохранить комментарий. Попробуйте ещё раз.' => 'Could not save the comment. Please try again.',
        'Только для зарегистрированных пользователей!' => 'Registered users only!',
        'Ошибка при отправке комментария!' => 'Error posting comment!',
        'Ошибка связи при отправке комментария!' => 'Network error while posting comment!',
        'Продвинуть это видео в блоке популярных?' => 'Promote this video in the popular block?',
        'Забанить автора и удалить канал вместе со всеми видео?' => 'Ban the author and delete the channel with all videos?',
        'Включить теневой бан для канала автора?' => 'Enable shadowban for this author\'s channel?',
        'Удалить это видео?' => 'Delete this video?',
        'Продвинуть видео' => 'Promote video',
        'Забанить автора' => 'Ban author',
        'Теневой бан' => 'Shadowban',
        'Удалить видео' => 'Delete video',
        'Кажется, у вас либо отключён JavaScript, либо установлена ​​старая версия Flash Player.' => 'It appears you have JavaScript turned off, or an old version of Adobe Flash Player.',
        'Нажмите здесь' => 'Click here',
        'чтобы загрузить последнюю версию Flash Player.' => 'to get the latest Flash Player.',
        'Вы знаете' => 'Do you know',
        'Зарегистрируйтесь' => 'Sign up',
        'или' => 'or',
        'Этот пользователь отключил возможность комментирования своего профиля.' => 'This user has disabled comments on their profile.',
        'Публичные видео' => 'Public Videos',
        'Видео от ' => 'Videos From ',
        'Канал ' => 'Channel ',
        'Текст:' => 'Text:',
        'От:' => 'From:',
        'Дата:' => 'Date:',
        '):' => '):',
        'Конвертируется…' => 'Processing…',
        'Введите название видео.' => 'Please enter a video title.',
        'Введите хотя бы один тег!' => 'Please enter at least one tag!',
        'Описание не должно превышать 5000 символов.' => 'Description must be 5000 characters or less.',
        'Ошибка при загрузке видео. Возможно, файл превышает лимит?' => 'Error uploading video. The file may be too large.',
        'Файл слишком большой! Максимальный размер: 1000 МБ.' => 'File is too large! Maximum size is 1000 MB.',
        'Видео добавлено в очередь обработки. Оно появится после завершения конвертации. <a href="index.php">На главную</a>' => 'Your video has been queued for processing. It will appear after conversion. <a href="index.php">Home</a>',
        'Видео успешно загружено! <a href="index.php">На главную</a>' => 'Video uploaded! <a href="index.php">Home</a>',
        'Янв' => 'Jan',
        'Фев' => 'Feb',
        'Мар' => 'Mar',
        'Апр' => 'Apr',
        'Май' => 'May',
        'Июн' => 'Jun',
        'Июл' => 'Jul',
        'Авг' => 'Aug',
        'Сен' => 'Sep',
        'Окт' => 'Oct',
        'Ноя' => 'Nov',
        'Дек' => 'Dec',
        'Возраст:' => 'Age:',
        'Веб-сайт:' => 'Website:',
        'Последний вход:' => 'Last Sign In:',
        'Оставить комментарий' => 'Leave a Comment',
        'Комментарии о пользователе' => 'Channel Comments',
        'Профиль ' => 'Profile ',
        'Публичные видео // ' => 'Public Videos // ',
        'Мои видео ' => 'My Videos ',
        'Канал не найден' => 'Channel not found',
        'Вход' => 'Log In',
        'Повторите пароль:' => 'Retype Password:',
        'Email:' => 'Email:',
        'Проверочный вопрос:' => 'Captcha:',
        'Зарегистрироваться' => 'Sign Up',
        'Пользователь с таким именем уже существует.' => 'That username is already taken.',
        'Пользователь с таким email уже существует.' => 'That email is already taken.',
        'Пароли не совпадают.' => 'Passwords do not match.',
        'Пароль должен содержать минимум 6 символов.' => 'Password must be at least 6 characters.',
        'Пожалуйста, заполните все обязательные поля.' => 'Please fill in all required fields.',
        'Неверный ответ на проверочный вопрос.' => 'Incorrect captcha answer.',
        'Не удалось создать аккаунт.' => 'Could not create the account.',
        'Ошибка базы данных.' => 'Database error.',
        'Сайт для вас недоступен.' => 'This site is unavailable for you.',
        'Ваш IP-адрес находится в черном списке. Пожалуйста, свяжитесь с администрацией сайта.' => 'Your IP address is blacklisted. Please contact the site administrator.',
        'Нет видео.' => 'No videos.',
        'Страницы:' => 'Pages:',
        'Следующая' => 'Next',
        'Предыдущая' => 'Previous',
        'На главную' => 'Home',
        'Добавить в друзья' => 'Add as Friend',
        'Убрать из друзей' => 'Remove Friend',
        'Отправить сообщение' => 'Send Message',
        'Теги:' => 'Tags:',
        'Описание:' => 'Description:',
        'Название:' => 'Title:',
        'Файл:' => 'File:',
        'Далее' => 'Next',
        'Назад' => 'Back',
        'Отмена' => 'Cancel',
        'Сохранить' => 'Save',
        'Удалить' => 'Delete',
        'Подтвердить' => 'Confirm',
        'URL видео:' => 'Video URL:',
        'Embed:' => 'Embed:',
        'Похожие видео' => 'Related Videos',
        'ещё' => 'more',
        'всего' => 'total',
        'Показано' => 'Showing',
        'из' => 'of',
        'Ещё видео' => 'More Videos',
        'Забыли пароль?' => 'Forgot your password?',
        'Войти' => 'Log In',
        'Результаты поиска' => 'Search Results',
        'Результаты поиска:' => 'Search Results:',
        'Возраст:' => 'Age:',
        'Теги:' => 'Tags:',
        'Введите один или несколько тегов, описывающих ваше видео, через пробел.' => 'Enter one or more tags, separated by spaces, describing your video.',
        'Лучше использовать релевантные ключевые слова, чтобы другие пользователи могли найти ваше видео!' => 'Use relevant keywords so other people can find your video!',
        'Макс. размер файла: 1000 МБ. Не загружайте материалы, нарущающие авторские права.' => 'Max file size: 1000 MB. Do not upload copyrighted material.',
        'После загрузки, вы можете редактировать или удалить это видео в любое время в разделе "Мои видео".' => 'After uploading, you can edit or delete this video anytime from "My Videos".',
        'видео будет доступно всем.' => 'the video will be visible to everyone.',
        'видео будет доступно только по ссылке.' => 'the video will only be available via a link.',
        'ПОЖАЛУЙСТА, ПОДОЖДИТЕ, ЭТО МОЖЕТ ЗАНЯТЬ НЕСКОЛЬКО МИНУТ.' => 'PLEASE BE PATIENT, THIS MAY TAKE A FEW MINUTES.',
        'ДАЖЕ ЕСЛИ СТРАНИЦА ОБНОВИЛАСЬ БЕЗ ПОДТВЕРЖДЕНИЯ, ВАШЕ' => 'EVEN IF THE PAGE REFRESHES WITHOUT CONFIRMATION, YOUR',
        'ВИДЕО БУДЕТ ОТПРАВЛЕНО НА ОБРАБОТКУ.' => 'VIDEO WILL STILL BE SENT FOR PROCESSING.',
        'Введите название видео.' => 'Please enter a video title.',
        'Введите хотя бы один тег!' => 'Please enter at least one tag!',
        'Описание не должно превышать 5000 символов.' => 'Description must be 5000 characters or less.',
        'Ошибка при загрузке видео. Возможно, файл превышает лимит?' => 'Error uploading the video. The file may exceed the size limit.',
        'Файл слишком большой! Максимальный размер: 1000 МБ.' => 'File too large! Maximum size: 1000 MB.',
        'RetroShow - это небольшой сайт, который стилизован под YouTube образца августа 2005 года, хотя и не повторяет его полностью (поскольку наша конечная цель - не воспроизведение YouTube один в один).' => 'RetroShow is a small site styled after YouTube as of August 2005, though it is not a 1:1 recreation (that is not our goal).',
        'RetroShow - это способ поделиться своими видео с теми, кто вам дорог. С RetroShow вы можете:' => 'RetroShow is a way to share your videos with the people who matter to you. With RetroShow you can:',
        'Демонстрировать свои любимые видео всему миру' => 'Show off your favorite videos to the world',
        'Снимать на видео своих собак, кошек и других домашних животных' => 'Take videos of your dogs, cats, and other pets',
        'Публиковать в блоге видео, снятые на цифровую камеру или мобильный телефон' => 'Blog videos taken with a digital camera or cell phone',
        'Безопасно и конфиденциально показывать видео своим друзьям и близким по всему миру' => 'Securely and privately show videos to friends and family around the world',
        '... и многое, многое другое!' => '... and much, much more!',
        'О: Вы можете загружать любые личные видео, которыми хотите поделиться со всем миром. Мы не допускаем обнажённую натуру, и ваше видео должно быть приемлемым для любой аудитории.' => 'A: You can upload any personal video you want to share with the world. We do not allow nudity, and your video must be appropriate for all audiences.',
        'О: Ограничений по времени для вашего видео нет, но размер загружаемого видеофайла не должен превышать 1 ГБ.' => 'A: There is no time limit, but the uploaded video file must not exceed 1 GB.',
        'О: RetroShow принимает видеофайлы с большинства цифровых камер и мобильных телефонов в форматах .MP4, .WEBM, .AVI, .MOV, .FLV, .MKV и другие.' => 'A: RetroShow accepts video files from most digital cameras and cell phones in .MP4, .WEBM, .AVI, .MOV, .FLV, .MKV and other formats.',
        'Связь с администрацией' => 'Contact Us',
        'Если у вас есть какие-либо вопросы или предложения по сайту, заполните форму обратной связи' => 'If you have any questions or suggestions about the site, fill out the contact form',
        'здесь' => 'here',
        'ничего не найдено.' => 'no results found.',
        'Видео не найдено или у вас нет прав для его редактирования.' => 'Video not found, or you do not have permission to edit it.',
        'Входящие' => 'Inbox',
        'Исходящие' => 'Sent',
        'Тема:' => 'Subject:',
        'От:' => 'From:',
        'Кому:' => 'To:',
        'Дата:' => 'Date:',
        'Ответить' => 'Reply',
        'Нет сообщений.' => 'No messages.',
        'Нет друзей.' => 'No friends yet.',
        'Нет избранного.' => 'No favorites yet.',
        'Убрать это видео из избранного?' => 'Remove this video from Favorites?',
        'Конвертируется' => 'Processing',
        'приватное' => 'private',
        'открытое' => 'public',
        'Личное' => 'Private',
        'Открытое' => 'Public',
        'Код для вставки:' => 'Embed Code:',
        'Ссылка на видео:' => 'Video Link:',
        'Показать' => 'Show',
        'Скрыть' => 'Hide',
        'ещё комментарии' => 'more comments',
        'Прикрепить видео:' => 'Attach a video:',
        'не прикреплять' => '(none)',
        'Мои видео:' => 'My Videos:',
        'Из избранного:' => 'From Favorites:',
        'Текст комментария:' => 'Comment:',
        'оценок' => 'ratings',
        'оценка' => 'rating',
        'оценки' => 'ratings',
        'Просмотров' => 'Views',
        'Комментариев' => 'Comments',
        'Загружено' => 'Added',
        'Канал' => 'Channel',
        'Подробнее' => 'More',
        'Меньше' => 'Less',
        'меньше' => 'less',
        'Смотреть видео' => 'Watch Videos',
        'Загрузить видео' => 'Upload Videos',
        'Пригласить друзей' => 'Invite Friends',
        'Января' => 'January',
        'Февраля' => 'February',
        'Марта' => 'March',
        'Апреля' => 'April',
        'Мая' => 'May',
        'Июня' => 'June',
        'Июля' => 'July',
        'Августа' => 'August',
        'Сентября' => 'September',
        'Октября' => 'October',
        'Ноября' => 'November',
        'Декабря' => 'December',
        'января' => 'January',
        'февраля' => 'February',
        'марта' => 'March',
        'апреля' => 'April',
        'мая' => 'May',
        'июня' => 'June',
        'июля' => 'July',
        'августа' => 'August',
        'сентября' => 'September',
        'октября' => 'October',
        'ноября' => 'November',
        'декабря' => 'December',
        'Про RetroShow' => 'About RetroShow',
        'Что такое RetroShow?' => 'What is RetroShow?',
        'Зарегистрируйтесь сейчас' => 'Sign up now',
        'Спасибо!' => 'Thank you!',
        'Связь с администрацией' => 'Contact Us',
        'В: Какие видео я могу загружать?' => 'Q: What kind of videos can I upload?',
        'В: Какова продолжительность моего видео?' => 'Q: How long can my video be?',
        'В: Какие форматы видеофайлов я могу загружать?' => 'Q: What video file formats can I upload?',
        'В: Как я могу улучшить свои видео?' => 'Q: How can I improve my videos?',
        'В: Сохраняю ли я авторские права и другие законные права на свои видео?' => 'Q: Do I retain copyright and other legal rights to my videos?',
        'В: Какова ваша политика в отношении нарушения авторских прав?' => 'Q: What is your policy on copyright infringement?',
        'В: Как сообщить о нарушении авторских прав?' => 'Q: How do I report copyright infringement?',
        'В: Что делать, если меня ложно обвинили в нарушении авторских прав?' => 'Q: What if I am falsely accused of copyright infringement?',
        'В: Что вы делаете, чтобы предотвратить появление на RetroShow контента, нарушающего ваши правила?' => 'Q: What do you do to prevent content that violates your policies from appearing on RetroShow?',
        'здесь' => 'here',
        'этой форме' => 'this form',
        'Информация о профиле' => 'Profile Information',
        'Личная информация' => 'Personal Information',
        'Email адрес:' => 'Email Address:',
        'Показывать:' => 'Show:',
        'Да' => 'Yes',
        'Нет' => 'No',
        'Комментарии к каналу' => 'Channel Comments',
        'Разрешить комментарии' => 'Allow comments',
        'Загрузка запрещена.' => 'Uploads are disabled.',
        'Загрузка видео для вашего IP адреса запрещена.' => 'Uploads from your IP address are not allowed.',
        'Ошибка при сохранении видео. Существует ли папка uploads и есть ли права на её запись?' => 'Could not save the video. Check that the uploads folder exists and is writable.',
        'Ошибка постановки видео в очередь обработки.' => 'Could not queue the video for processing.',
        'Ошибка при добавлении видео в очередь. Попробуйте ещё раз.' => 'Could not add the video to the queue. Please try again.',
        'Шаг 1' => 'Step 1',
        'Шаг 2' => 'Step 2',
        'Выберите видеофайл' => 'Select a video file',
        'Название видео' => 'Video Title',
        'Описание' => 'Description',
        'Теги' => 'Tags',
        'Вещание' => 'Broadcast',
        'Для всех' => 'Public',
        'Только для меня' => 'Private',
        'Продолжить' => 'Continue',
        'Загрузить' => 'Upload',
        'Онлайн' => 'Online',
        'Сейчас на сайте' => 'Currently Online',
        'Статистика' => 'Statistics',
        'пользователей' => 'users',
        'видео' => 'Videos',
        'нет результатов' => 'no results',
        'Найдено:' => 'Found:',
        'Сортировка:' => 'Sort:',
        'по релевантности' => 'by relevance',
        'по дате' => 'by date',
        'по просмотрам' => 'by views',
        'Друг' => 'Friend',
        'в друзьях' => 'is a friend',
        'Ещё нет избранных видео.' => 'No favorite videos yet.',
        'Ещё нет друзей.' => 'No friends yet.',
        'Ещё нет видео.' => 'No videos yet.',
        'Это видео обрабатывается и пока недоступно.' => 'This video is still processing and is not available yet.',
        'Видео добавлено в очередь обработки. Оно появится после завершения конвертации.' => 'Your video has been queued for processing. It will appear after conversion.',
        'Готово. Видео загружено.' => 'Done. Video uploaded.',
        'Убрать из избранного' => 'Remove from Favorites',
        'Добавлено в избранное' => 'Added to Favorites',
        'раз' => 'times',
        'Комментарии (всего' => 'Comments (',
        'Канал не найден!' => 'Channel not found!',
        'Поделитесь этим видео с друзьями! Скопируйте и вставьте ссылку выше в Email или на сайт.' => 'Share this video with friends! Copy and paste the link above into an email or website.',
        'для' => 'for',
        'Публикуемые вами комментарии будут видны всем, кто просматривает профиль пользователя' => 'Comments you post will be visible to anyone viewing',
        'Оставить новый комментарий' => 'Add a New Comment',
        'Отправить комментарий' => 'Post Comment',
        'Любимые теги:' => 'Favorite Tags:',
        'У вас нет отправленных сообщений.' => 'You have no sent messages.',
        'Исходящие сообщения' => 'Sent Messages',
        'Сообщения // Исходящие сообщения' => 'Messages // Sent',
        'Сообщения // Входящие' => 'Messages // Inbox',
        'Входящие сообщения' => 'Inbox',
        'Отправлено:' => 'Sent:',
        'Отправить сообщение' => 'Send Message',
        'Введите тему или текст сообщения.' => 'Please enter a subject or message.',
        'Тема слишком длинная.' => 'Subject is too long.',
        'Сообщение слишком длинное.' => 'Message is too long.',
        'Пользователь не найден.' => 'User not found.',
        'Нельзя отправить сообщение самому себе.' => 'You cannot send a message to yourself.',
        'Сообщение отправлено.' => 'Message sent.',
        'Кому' => 'To',
        'Ваша почта:' => 'Your Email:',
        'Вопрос о сайте' => 'General Question',
        'Ошибка или баг' => 'Bug Report',
        'Предложение по улучшению' => 'Feature Request',
        'Вопрос по контенту' => 'Content Question',
        'Другое' => 'Other',
        'Выберите тему.' => 'Please choose a subject.',
        'Введите сообщение.' => 'Please enter a message.',
        'Введите корректный email.' => 'Please enter a valid email.',
        'Сообщение отправлено администраторам в ЛС.' => 'Your message was sent to the administrators.',
        'Не удалось отправить сообщение!' => 'Could not send the message!',
        'Отправить' => 'Send',
        'Если у вас есть какие-либо вопросы или предложения по сайту, заполните и отправьте форму ниже. Учтите, что ваше сообщение будет доставлено всем администраторам веб-ресурса. Ваш IP-адрес будет сохранён и виден администраторам, чтобы предотвратить спам-атаки, а ваша почта также будет видна только администраторам, чтобы они могли отправить ответное письмо.' => 'If you have questions or suggestions about the site, fill out the form below. Your message will be delivered to all site administrators. Your IP address will be saved and visible to admins to prevent spam, and your email will only be visible to admins so they can reply.',
        'Пожалуйста, введите имя пользователя.' => 'Please enter a username.',
        'Такой пользователь не найден.' => 'That user was not found.',
        'У этого пользователя не указан email, восстановить пароль невозможно.' => 'This user has no email on file, so the password cannot be reset.',
        'На E-mail, указанный при регистрации, отправлена ссылка для смены пароля.' => 'A password reset link was sent to the email address on this account.',
        'Не удалось отправить письмо. Попробуйте позже.' => 'Could not send the email. Please try again later.',
        'Забыли пароль? Не проблема!' => 'Forgot your password? No problem!',
        'Просто введите ваше имя пользователя, и мы отправим на' => 'Just enter your username, and we will send a password reset link to the',
        'специальную ссылку для смены пароля.' => 'on file.',
        'Выслать ссылку' => 'Send Link',
        'Приглашения отправлены!' => 'Invites sent!',
        'Приглашения не отправлены! Попробуйте еще раз.' => 'Invites were not sent! Please try again.',
        'RetroShow становится интереснее с друзьями!' => 'RetroShow is more fun with friends!',
        'Хотите поделиться интересными или забавными видео с коллегами и друзьями? Пригласите их присоединиться!' => 'Want to share interesting or funny videos with coworkers and friends? Invite them to join!',
        'Здравствуйте,' => 'Hi,',
        'RetroShow - это отличный сайт для обмена и хранения личных видео. Я использую RetroShow, чтобы делиться видео с друзьями и семьёй. Я бы хотел добавить вас в список людей, с которыми могу делиться своими видео.' => 'RetroShow is a great site for sharing and storing personal videos. I use RetroShow to share videos with friends and family. I would like to add you to the list of people I can share my videos with.',
        'Ваше личное сообщение:' => 'Your personal message:',
        'Вы слышали про RetroShow? Мне очень нравится этот сайт.' => 'Have you heard about RetroShow? I really like this site.',
        'Спасибо,' => 'Thanks,',
        'ваше_имя' => 'your_name',
        'Отправить приглашения' => 'Send Invites',
        'Перейти на RetroShow' => 'Go to RetroShow',
        'Спасибо!' => 'Thank You!',
        'разработчик движка сайта.' => 'site engine developer.',
        'первый пользователь сайта, который занимался тестированием.' => 'the first user of the site, who helped with testing.',
        'О: Мы рекомендуем вам редактировать видео с помощью таких программ, как Windows MovieMaker (входит в комплект каждой установки Windows) или Apple iMovie. С помощью этих программ вы можете легко редактировать видео, добавлять звуковые дорожки и т. д.' => 'A: We recommend editing your videos with programs like Windows Movie Maker (included with Windows) or Apple iMovie. With these programs you can easily edit video, add soundtracks, and more.',
        'О: Да. Вы сохраняете все права на свой контент. RetroShow не берет на себя никаких авторских прав на ваши материалы.' => 'A: Yes. You retain all rights to your content. RetroShow does not take any copyrights on your material.',
        'Однако это оставляет большой простор для творчества! У вас есть' => 'But that still leaves plenty of room for creativity! Do you have a',
        'собака' => 'dog',
        'кошка' => 'cat',
        'Это лишь некоторые примеры видео, которые загружают наши пользователи. В конце концов, вы знаете себя лучше всех. Что бы вы хотели заснять на видео?' => 'These are just a few examples of videos our users upload. In the end, you know yourself best. What would you like to capture on video?',
        'Если у вас есть какие-либо вопросы или предложения по сайту, заполните форму обратной связи' => 'If you have any questions or suggestions about the site, fill out the contact form',
        'здесь' => 'here',
        'эту форму' => 'this form',
        'В: Какова ваша политика в отношении нарушения авторских прав?' => 'Q: What is your policy on copyright infringement?',
        'О: RetroShow уважает права правообладателей и издателей и принимает видео только от лиц, обладающих всеми необходимыми правами на загруженный материал. Наша политика заключается в том, чтобы реагировать на любые уведомления о предполагаемых нарушениях в соответствии с Законом об авторском праве в цифровую эпоху (DMCA). Если мы получим уведомление или у нас появятся основания полагать, что предоставленный вами контент нарушает авторские права третьих лиц, ваш аккаунт может быть удален, а видео удалено с RetroShow.' => 'A: RetroShow respects the rights of copyright holders and publishers and accepts videos only from people who have all necessary rights to the uploaded material. Our policy is to respond to any notices of alleged infringement in accordance with the Digital Millennium Copyright Act (DMCA). If we receive a notice or have reason to believe that content you provided infringes third-party copyrights, your account may be terminated and the video removed from RetroShow.',
        'В: Как сообщить о нарушении авторских прав?' => 'Q: How do I report copyright infringement?',
        'О: Если вы считаете, что кто-то другой загрузил ваш контент, защищенный авторским правом, без вашего разрешения, мы рекомендуем вам связаться с этим лицом для разрешения любых разногласий напрямую. Вы также можете обратиться в нашу службу поддержки, используя' => 'A: If you believe someone else uploaded your copyrighted content without permission, we recommend contacting that person to resolve the dispute directly. You can also contact our support using',
        'чтобы получить инструкции о том, как отправить уведомление о нарушении авторских прав в RetroShow.' => 'to get instructions on how to send a copyright infringement notice to RetroShow.',
        'В: Что делать, если меня ложно обвинили в нарушении авторских прав?' => 'Q: What if I am falsely accused of copyright infringement?',
        'О: Мы сообщим вам, если получим жалобу на нарушение авторских прав в отношении любого вашего видеоконтента, размещенного на RetroShow. Мы предоставим вам возможность отреагировать соответствующим образом.' => 'A: We will notify you if we receive a copyright complaint about any of your video content on RetroShow. We will give you an opportunity to respond appropriately.',
        'В: Что вы делаете, чтобы предотвратить появление на RetroShow контента, нарушающего ваши правила?' => 'Q: What do you do to prevent content that violates your policies from appearing on RetroShow?',
        'О: Мы проводим предварительную проверку загруженных видео как вручную, так и автоматически. Хотя мы делаем все возможное для выявления и удаления видео, нарушающих наши правила, наш процесс проверки в первую очередь ориентирован на удаление контента для взрослых или очевидных нарушений авторских прав и не является абсолютно безупречным. Тем не менее, мы призываем наших зрителей сообщать нам, если они обнаружат нарушения политики или проблемы с авторскими правами. У нас есть процесс рассмотрения сообщений о нарушениях политики и реагирования на сообщения о нарушениях авторских прав в соответствии с Законом об авторском праве в цифровую эпоху.' => 'A: We review uploaded videos both manually and automatically. While we do our best to find and remove videos that violate our rules, our review process is primarily focused on adult content or obvious copyright violations and is not perfect. We still encourage viewers to tell us if they find policy violations or copyright issues. We have a process for reviewing policy reports and responding to copyright notices under the DMCA.',
        'Однако это оставляет большой простор для творчества! У вас есть' => 'But that still leaves plenty of room for creativity! Do you have a',
        'или' => 'or',
        'Вы отдыхали в' => 'Been on vacation in',
        'Вы живёте в' => 'Do you live in',
        'Это лишь некоторые примеры видео, которые загружают наши пользователи. В конце концов, вы знаете себя лучше всех. Что бы вы хотели заснять на видео?' => 'These are just a few examples of videos our users upload. In the end, you know yourself best. What would you like to capture on video?',
        'Редактирование видео' => 'Edit Video',
        'Изменения успешно сохранены.' => 'Your changes have been saved.',
        'Сохранить изменения' => 'Update Video',
        'Ошибка при сохранении изменений.' => 'Could not save the changes.',
        'Удаление аккаунта' => 'Delete Account',
        'Назад к настройкам' => 'Back to My Account',
        'Аккаунт успешно удалён!' => 'Your account has been deleted!',
        'Удаление аккаунта приведёт к безвозвратному удалению всех ваших данных (видео, комментарии, избранное и т.д.) с RetroShow. Это действие необратимо.' => 'Deleting your account will permanently remove all of your data (videos, comments, favorites, etc.) from RetroShow. This cannot be undone.',
        'Введите ваш пароль:' => 'Enter your password:',
        'Удалить аккаунт' => 'Delete Account',
        'Неверный пароль!' => 'Incorrect password!',
        'Удалить сообщение' => 'Delete Message',
        'Подтвердите: сообщение будет удалено без возможности восстановления.' => 'Confirm: this message will be deleted and cannot be recovered.',
        'Назад' => 'Back',
        'Перейти на канал.' => 'Go to channel.',
        'Перейти к ветке комментариев под видео.' => 'Go to the comment thread on the video.',
        'Перейти к комментариям к видео.' => 'Go to the video comments.',
        'Забыли имя пользователя' => 'Forgot Username',
        'Забыли ваше имя пользователя? Не проблема!' => 'Forgot your username? No problem!',
        'Просто введите E-Mail адрес, с которым вы регистрировались, и мы покажем вам ваше имя пользователя.' => 'Just enter the email address you signed up with, and we will show you your username.',
        'E-Mail адрес:' => 'Email Address:',
        'Получить имя!' => 'Get Username!',
        'Имя:' => 'Name:',
        'видео будет доступно всем.' => 'share your video with the world! (Recommended)',
        'видео будет доступно только по ссылке.' => 'only share your video with people who have the link.',
        'Язык сайта:' => 'Site language:',
        'Русский' => 'Russian',
        'Теперь баннер скрыт. Язык можно сменить позже в настройках аккаунта (после входа) и сохранить его там.' => 'This banner is now hidden. After you sign in, you can change and save the site language in My Account.',
        '<< Назад' => '<< Back',
        'Далее >>' => 'Next >>',
        'Управление блогом' => 'Blog',
        'Опубликовать новый пост' => 'Publish a new post',
        'Текст поста (рус.):' => 'Post text (RU):',
        'Текст поста (англ.):' => 'Post text (EN):',
        'Опубликовать пост' => 'Publish post',
        'Текст новости (рус.):' => 'News text (RU):',
        'Текст новости (англ.):' => 'News text (EN):',
        'Добавить новость' => 'Save news',
        'Забыли имя пользователя' => 'Forgot Username',
        'Пожалуйста, введите ваш email адрес.' => 'Please enter your email address.',
        'Пожалуйста, введите корректный email адрес.' => 'Please enter a valid email address.',
        'Аккаунт с таким E-Mail адресом не найден.' => 'No account was found with that email address.',
        'Ваше имя пользователя: ' => 'Your username: ',
        'Ежемесячный конкурс' => 'Monthly Contest',
        'Что это?' => 'What is this?',
        'Ля-ля-ля.' => 'La-la-la.',
        'Этот месяц (Сентябрь 2005)' => 'This month (September 2005)',
        'Ага-ага-ага.' => 'Uh-huh.',
        'Как принять участие?' => 'How do I enter?',
        'Угу-угу-угу.' => 'Yep.',
        'Кто побеждает?' => 'Who wins?',
        'Я.' => 'Me.',
        'Приз?' => 'Prize?',
        'Не придумал.' => "Haven't thought of one.",
        'Расписание конкурсов видео' => 'Video contest schedule',
        'Сентябрь 2005:' => 'September 2005:',
        'Октябрь 2005:' => 'October 2005:',
        'Ноябрь 2005:' => 'November 2005:',
        'Декабрь 2005:' => 'December 2005:',
        'Будет объявлено' => 'To be announced',
        'Есть предложение для ежемесячного конкурса видео? Пожалуйста,' => 'Have an idea for the monthly video contest? Please',
        'расскажите нам' => 'tell us',
        'об этом.' => 'about it.',
        'Удаление видео' => 'Delete Video',
        'Видео не найдено.' => 'Video not found.',
        'Вернуться к моим видео' => 'Back to My Videos',
        'Видео не найдено или у вас нет прав для его удаления.' => 'Video not found, or you do not have permission to delete it.',
        'Ошибка при удалении видео.' => 'Error deleting the video.',
        'Назад к редактированию' => 'Back to editing',
        'Удаление этого видео приведёт к безвозвратному удалению файла видео, его обложки, комментариев, оценок, просмотров и ссылок в избранном.' => 'Deleting this video will permanently remove the video file, its thumbnail, comments, ratings, views, and favorite links.',
        'Это действие необратимо.' => 'This cannot be undone.',
        'Вы действительно хотите удалить видео' => 'Are you sure you want to delete the video',
        'Администрирование' => 'Administration',
        'Как дела у RetroShow?' => 'How is RetroShow doing?',
        'Прямо сейчас у нас:' => 'Right now we have:',
        'видео' => 'Videos',
        'просмотров' => 'views',
        'сообщений' => 'messages',
        'комментариев' => 'comments',
        'видео в избранном' => 'favorited videos',
        'пользователей' => 'users',
        'Разве это не круто?' => "Isn't that cool?",
        'Текст новости слишком длинный (макс. 500 символов).' => 'News text is too long (max 500 characters).',
        'Новость успешно добавлена!' => 'News saved!',
        'Текст поста не может быть пустым.' => 'Post text cannot be empty.',
        'Пост успешно опубликован.' => 'Post published.',
        'Ошибка публикации поста.' => 'Could not publish the post.',
        'Укажите адрес вида http://... или https://...' => 'Enter an address like http://... or https://...',
        'Слишком длинный адрес.' => 'Address is too long.',
        'Настройки конвертации сохранены.' => 'Conversion settings saved.',
        'Не удалось сохранить настройки.' => 'Could not save settings.',
        'Настройки сохранены.' => 'Settings saved.',
        'Не удалось сохранить настройку рекомендаций.' => 'Could not save recommendation setting.',
        'Неверный IP адрес.' => 'Invalid IP address.',
        'Этот IP уже в бане.' => 'This IP is already banned.',
        'IP успешно добавлен в бан.' => 'IP banned.',
        'IP удалён из бана.' => 'IP unbanned.',
        'По этому IP не найдено загруженных видео в файловом логе.' => 'No uploaded videos were found for this IP in the file log.',
        'Укажите логин канала.' => 'Enter the channel login.',
        'Канал удалён.' => 'Channel deleted.',
        'Ошибка удаления видео канала.' => 'Could not delete channel videos.',
        'Логи очищены.' => 'Logs cleared.',
        'Внешний сервер конвертации:' => 'External conversion server:',
        'включить' => 'enable',
        'Адрес:' => 'Address:',
        'Для использования внешнего сервера, запустите его при помощи скрипта по пути' => 'To use an external server, start it with the script at',
        'при помощи интерпретатора Python.' => 'using the Python interpreter.',
        'Сохранить' => 'Save',
        'включать персональные рекомендации у новых пользователей по умолчанию' => 'enable personalized recommendations for new users by default',
        'Бан IP.' => 'IP Ban.',
        'Забанить IP' => 'Ban IP',
        'Разбанить IP' => 'Unban IP',
        'Показать баны' => 'Show bans',
        'Скрыть баны' => 'Hide bans',
        'Текущие баны:' => 'Current bans:',
        'Банов IP пока нет.' => 'No IP bans yet.',
        'Удалить все видео по IP.' => 'Delete all videos by IP.',
        'Удалить все видео по этому IP?' => 'Delete all videos for this IP?',
        'Удалить видео по IP' => 'Delete videos by IP',
        'Удалить канал.' => 'Delete channel.',
        'Удалить канал?' => 'Delete channel?',
        'Канал:' => 'Channel:',
        'Удалить канал' => 'Delete channel',
        'Удалить все видео канала.' => 'Delete all videos on a channel.',
        'Удалить все видео указанного канала?' => 'Delete all videos on this channel?',
        'Удалить видео канала' => 'Delete channel videos',
        'Логи (последние 200).' => 'Logs (last 200).',
        'Поиск по логам:' => 'Search logs:',
        'Искать' => 'Search',
        'Сброс' => 'Reset',
        'Очистить лог-файл полностью?' => 'Clear the log file completely?',
        'Очистить логи' => 'Clear logs',
        'Логи пусты.' => 'Logs are empty.',
        'Удалено видео по IP:' => 'Videos deleted for IP:',
        'Удалено видео канала:' => 'Channel videos deleted:',
        'Язык сайта по умолчанию:' => 'Default site language:',
        'для гостей и новых аккаунтов' => 'for guests and new accounts',
        'Язык по умолчанию сохранён.' => 'Default language saved.',
        'Не удалось сохранить язык по умолчанию.' => 'Could not save the default language.',
        'Плохо' => 'Poor',
        'Ничего особенного' => 'Nothing special',
        'Стоит посмотреть' => 'Worth watching',
        'Довольно круто' => 'Pretty cool',
        'Отлично!' => 'Awesome!',
        'Сентябрьский конкурс!' => 'September Contest!',
        'Присоединяйтесь к конкурсу сейчас!' => 'Join the contest now!',
        'Тегов пока нет!' => 'No tags yet!',
        'Введите один или несколько тегов, разделённых пробелами. Например:' => 'Enter one or more tags, separated by spaces. For example:',
        'На главную' => 'Home',
        'Ошибка при добавлении видео в очередь. Попробуйте ещё раз.' => 'Could not add the video to the queue. Please try again.',
        'Ошибка при сохранении видео. Существует ли папка uploads и есть ли права на её запись?' => 'Could not save the video. Does the uploads folder exist and is it writable?',
        'Видео успешно загружено!' => 'Video uploaded!',
        'Ошибка постановки видео в очередь обработки.' => 'Could not queue the video for processing.',
    ];
    return $map;
}

function t($text) {
    $text = (string)$text;
    if ($text === '' || !site_lang_is_en()) {
        return $text;
    }
    $map = site_lang_en_map();
    return $map[$text] ?? $text;
}

function t_html($text): string {
    return htmlspecialchars(t($text), ENT_QUOTES, 'UTF-8');
}

function t_js_attr($text): string {
    return htmlspecialchars(json_encode(t($text), JSON_UNESCAPED_UNICODE), ENT_QUOTES, 'UTF-8');
}

function t_comments_heading($count): string {
    $count = (int)$count;
    if (site_lang_is_en()) {
        return 'Comments (' . $count . '):';
    }
    return 'Комментарии (всего ' . $count . '):';
}

function t_ratings_count($count): string {
    $n = abs((int)$count);
    if (site_lang_is_en()) {
        return (string)$n . ' ' . ($n === 1 ? 'rating' : 'ratings');
    }
    $n100 = $n % 100;
    $n1 = $n % 10;
    if ($n100 > 10 && $n100 < 20) {
        $w = 'оценок';
    } elseif ($n1 === 1) {
        $w = 'оценка';
    } elseif ($n1 >= 2 && $n1 <= 4) {
        $w = 'оценки';
    } else {
        $w = 'оценок';
    }
    return (string)$n . ' ' . $w;
}

function site_lang_url(string $lang): string {
    $script = basename((string)($_SERVER['SCRIPT_NAME'] ?? 'index.php'));
    $q = $_GET;
    $q['ui_lang'] = site_lang_normalize($lang);
    return $script . '?' . http_build_query($q);
}

function site_lang_switcher_html(): string {
    if (!empty($_SESSION['user']) || !empty($_COOKIE['lang_bar_off'])) {
        return '';
    }
    $cur = site_lang();
    $ru_img = '<img src="img/flags/Russia.png" width="16" height="11" border="0" alt="RU" style="vertical-align:middle;">';
    $en_img = '<img src="img/flags/United-States.png" width="16" height="11" border="0" alt="EN" style="vertical-align:middle;">';
    if ($cur === 'ru') {
        $ru_img = '<img src="img/flags/Russia.png" width="16" height="11" border="1" alt="RU" style="vertical-align:middle; border-color:#333333;">';
    } else {
        $en_img = '<img src="img/flags/United-States.png" width="16" height="11" border="1" alt="EN" style="vertical-align:middle; border-color:#333333;">';
    }
    $ru = ($cur === 'ru')
        ? $ru_img
        : '<a href="' . htmlspecialchars(site_lang_url('ru'), ENT_QUOTES, 'UTF-8') . '">' . $ru_img . '</a>';
    $en = ($cur === 'en')
        ? $en_img
        : '<a href="' . htmlspecialchars(site_lang_url('en'), ENT_QUOTES, 'UTF-8') . '">' . $en_img . '</a>';
    $close = htmlspecialchars(t('закрыть'), ENT_QUOTES, 'UTF-8');
    $label = htmlspecialchars(t('Язык:'), ENT_QUOTES, 'UTF-8');
    return '<td style="padding: 0px 5px 0px 5px;" id="guestLangBarSep">|</td>'
        . '<td id="guestLangBar">'
        . $label . ' ' . $ru . ' | ' . $en  . ' | '
        . '&nbsp;<a href="#" title="' . $close . '" onclick="return hideGuestLangBar();">[X]</a>'
        . '</td>';
}

function site_lang_switcher_script(): string {
    $lang_alert_js = json_encode(
        t('Теперь баннер скрыт. Язык можно сменить позже в настройках аккаунта (после входа) и сохранить его там.'),
        JSON_UNESCAPED_UNICODE
    );
    return '<script language="javascript" type="text/javascript">'
        . 'function hideGuestLangBar() {'
        . 'var ids = ["guestLangBar","guestLangBarSep"];'
        . 'for (var i = 0; i < ids.length; i++) {'
        . 'var el = document.getElementById ? document.getElementById(ids[i]) : (document.all ? document.all[ids[i]] : null);'
        . 'if (el) el.style.display = "none";'
        . '}'
        . 'document.cookie = "lang_bar_off=1; path=/";'
        . 'alert(' . $lang_alert_js . ');'
        . 'window.location.reload();'
        . 'return false;'
        . '}'
        . '</script>';
}

function site_lang_apply_request(): void {
    if (!isset($_GET['ui_lang'])) {
        return;
    }
    site_lang_set((string)$_GET['ui_lang']);
    $q = $_GET;
    unset($q['ui_lang']);
    $path = (string)(parse_url((string)($_SERVER['REQUEST_URI'] ?? '/'), PHP_URL_PATH) ?: 'index.php');
    $qs = http_build_query($q);
    header('Location: ' . $path . ($qs !== '' ? '?' . $qs : ''));
    exit;
}

function site_lang_apply_user(PDO $db, $login): void {
    $login = trim((string)$login);
    if ($login === '') {
        return;
    }
    try {
        $st = $db->prepare('SELECT ui_lang FROM users WHERE login = ? LIMIT 1');
        $st->execute([$login]);
        $v = $st->fetchColumn();
        if ($v !== false && $v !== null && $v !== '') {
            site_lang_set((string)$v);
        } else {
            site_lang_set(site_lang_default());
        }
    } catch (Exception $e) {
    }
}
